---
- name: Create backup dirs and scripts dir
  file:
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_name }}"
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ backup_scripts_path }}"
    - "{{ backup_dir_daily }}"
    - "{{ backup_dir_weekly }}"

- name: Template clean backup script
  template:
    src: ansible_postgres_backup_clean.sh.j2
    dest: "{{ backup_scripts_path }}/ansible_postgres_backup_clean.sh"
    owner: "{{ postgresql_user_name }}"
    group: "{{ postgresql_user_name }}"
    mode: 0755
    backup: true

- name: Add cron jobs
  cron:
    name: "PostgreSQL Backup Clean"
    user: postgres
    minute: "10"
    hour: "1"
    weekday: "6"
    job: "{{ backup_scripts_path }}/ansible_postgres_backup_clean.sh"
